# Generated by Django 5.1.3 on 2025-01-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("num_stars", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MusicCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("instrument", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        choices=[
                            ("MH", "Maharashtra"),
                            ("GJ", "Gujarat"),
                            ("DL", "Delhi"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "state",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_app.musician",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NewAppMode",
        ),
        migrations.AddField(
            model_name="musiccompany",
            name="artists",
            field=models.ManyToManyField(to="new_app.musician"),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="new_app.musician"
            ),
        ),
    ]
