# **PANDAS INTRODUCTION**


Pandas is a high-level data manipulation tool developed by Wes McKinney. This tool is essentially your data’s home. Through pandas, you get acquainted with your data by cleaning, transforming, and analyzing it. It is built on the Numpy package and its key data structure is called the DataFrame.

Pandas is an easy package to install. Open up your terminal program (for Mac users) or command line (for PC users) and install it using the following command:


In [ ]:
%pip install pandas

To import pandas we usually import it with a shorter name since it's used so much:


In [2]:
import pandas as pd  # aliasing

print(pd.__version__)

2.2.2


## **Core components of pandas: Series and DataFrames**

1. The primary two components of pandas are the Series and DataFrame.
2. A Series is essentially a column, and a DataFrame is a multi-dimensional table made up of a collection of Series.
3. DataFrames allow you to store and manipulate tabular data in rows of observations and columns of variables.

![image](https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png)

Now, DataFrames in Python are very similar: they come with the Pandas library, and they are defined as two-dimensional labeled data structures with columns of potentially different types. In general, you could say that the Pandas DataFrame consists of three main components: **the data, the index, and the columns**.

Firstly, the DataFrame can contain data that is:

1. **a Pandas DataFrame**

2. **a Pandas Series:** a one-dimensional labelled array capable of holding any data type with axis labels or index. An example of a Series object is one column from a DataFrame.

3. **a NumPy ndarray**, which can be a record or structured

4. **a two-dimensional ndarray**

5. **dictionaries of one-dimensional ndarray’s, lists, dictionaries or Series**


## **Pandas Dataframe**

There are many ways to create a DataFrame from scratch, but a great option is to just use a simple dict.

**For example:**


In [1]:
# importing pandas library with aliasing as pd
import pandas as pd

df_dict = {
    "COUNTRY": ["Brazil", "Russia", "India", "China", "South Africa", "New Zealand"],
    "CAPITAL": ["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria", None],
    "AREA": [8.516, 17.10, 3.286, 9.597, 1.221, None],
    "POPULATION": [200.4, 143.5, 1252, 1357, 52.98, None],
}

# print(df_dict)

# pd.DataFrame() function is used to create a dataframe in pandas
df = pd.DataFrame(df_dict)
print(df)
print(type(df))

        COUNTRY    CAPITAL    AREA  POPULATION
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98
5   New Zealand       None     NaN         NaN
<class 'pandas.core.frame.DataFrame'>


### **How did that work?**

Each (key, value) item in data corresponds to a column in the resulting DataFrame.

The Index of this DataFrame was given to us on creation as the numbers 0-4, but we could also create our own when we initialize the DataFrame.


In [18]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [19]:
# Set the index for df using dataframe index property
df.index = ["BR", "RU", "IN", "CH", "SA", "NZ"]
print(df)

         COUNTRY    CAPITAL    AREA  POPULATION
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98
NZ   New Zealand       None     NaN         NaN


In [20]:
df

COUNTRY    CAPITAL    AREA  POPULATION
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98
NZ   New Zealand       None     NaN         NaN

In [21]:
print(type(df.index))

<class 'pandas.core.indexes.base.Index'>


In [23]:
# set the index for df using index attribute
df_1 = pd.DataFrame(df_dict, index=["BR", "RU", "IN", "CH", "SA", "NZ"])
print(df_1)

         COUNTRY    CAPITAL    AREA  POPULATION
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98
NZ   New Zealand       None     NaN         NaN


## df.set_index() -> returns a new Dataframe with new index that you specified

In [3]:
# you can specify a particular column as index of your dataframe
df_dict = {
    "COUNTRY": ["Brazil", "Russia", "India", "China", "South Africa"],
    "CAPITAL": ["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
    "AREA": [8.516, 17.10, 3.286, 9.597, 1.221],
    "POPULATION": [200.4, 143.5, 1252, 1357, 52.98],
}
df_2 = pd.DataFrame(df_dict)
print(df_2.index)
df_2.set_index("COUNTRY")
print(df_2.index)
df_3 = df_2.set_index("COUNTRY")
print(df_3.index)
df_3

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=5, step=1)
Index(['Brazil', 'Russia', 'India', 'China', 'South Africa'], dtype='object', name='COUNTRY')


CAPITAL    AREA  POPULATION
COUNTRY                                    
Brazil         Brasilia   8.516      200.40
Russia           Moscow  17.100      143.50
India         New Delhi   3.286     1252.00
China           Beijing   9.597     1357.00
South Africa   Pretoria   1.221       52.98

After this if you will try to print your dataframe you will not get COUNTRY column as your index and that's because when you use **pd.set_index()** function, pandas creates a `copy of your dataframe` for that instance and does not modify the original dataframe. see below..


In [40]:
print(df_2)

        COUNTRY    CAPITAL    AREA  POPULATION
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


### inplace = True does not return a new DataFrame but edits the one it aldready have i.e inplace

In [41]:
df_3 = pd.DataFrame(df_dict)
df_3.set_index("COUNTRY", inplace=True)     
df_3.index

Index(['Brazil', 'Russia', 'India', 'China', 'South Africa'], dtype='object', name='COUNTRY')

In [42]:
print(df_3)

                CAPITAL    AREA  POPULATION
COUNTRY                                    
Brazil         Brasilia   8.516      200.40
Russia           Moscow  17.100      143.50
India         New Delhi   3.286     1252.00
China           Beijing   9.597     1357.00
South Africa   Pretoria   1.221       52.98


## **Pandas Inplace Attribute**

At its core, the inplace parameter helps you decide how you want to affect the underlying data of the Pandas object. Do you want to make a change to the dataframe object you are working on and overwrite what was there before? Or do you want to make a copy of the dataframe object and assign it to a different variable so you can modify that original data later? Those are the two questions you need to ask yourself. Your answers will help you determine if you need to set the inplace parameter to True or False.

![image](https://miro.medium.com/max/898/1*CkYtTM7RpMBB7mlqKwTSNg.png)


### **How to read in data?**

It’s quite simple to load data from various file formats into a DataFrame.

## **Reading data from CSVs**

### **What is csv?**

CSV stands for Comma Separated Values, A popular way of representing and storing tabular, column oriented data in a persistent storage. Pandas DataFrames are generally used for representing Excel Like Data In-Memory.

In the following code we are going to import the dataset from http://bit.ly/imdbratings . If you are having your dataset then instead of passing the url in the following code put your dataset location followed by the file name.

**Note:** CSV is not the only supported file in pandas you can also use html, excel, json and many more.


In [51]:
import pandas as pd

df = pd.read_csv("http://bit.ly/imdbratings")
# df = pd.read_csv('data/imdb_1000.csv')

# This will print 5 entries of datset from top
df.head()

star_rating                     title content_rating   genre  duration  \
0          9.3  The Shawshank Redemption              R   Crime       142   
1          9.2             The Godfather              R   Crime       175   
2          9.1    The Godfather: Part II              R   Crime       200   
3          9.0           The Dark Knight          PG-13  Action       152   
4          8.9              Pulp Fiction              R   Crime       154   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4  [u'John Travolta', u'Uma Thurman', u'Samuel L....

Now, we are going to explore the dataset by looking at the no. of entries, total columns, data type of each column.

By using attributes like **pd.columns** and **pd.index** you can go through the details and can find out some useful information.


In [31]:
df.index, type(df.index)

(RangeIndex(start=0, stop=979, step=1), pandas.core.indexes.range.RangeIndex)

Above code shows we have all total 979 entries counting from 0 with an interval of 1. **i.e. 0, 1, 2, 3, ......, 978**


In [50]:
df.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

## Data Types in Pandas

In **pandas**, data types are automatically inferred based on the values in a `DataFrame` or `Series`. The common data types used in pandas are:

- **Integer (`int64`)**: Represents integer values.
- **Float (`float64`)**: Represents floating-point numbers.
- **Boolean (`bool`)**: Represents `True` or `False`.

All other data types like **String**, **List**, **Dictionary**, etc., are categorized as **object**.

| Python Type   | Pandas Type | Example             |
|---------------|-------------|---------------------|
| `int`         | `int64`     | `1, 2, 3`           |
| `float`       | `float64`   | `1.0, 2.5, 3.14`    |
| `bool`        | `bool`      | `True, False`       |
| `str`, `list`, `dict`, ... | `object`   | `'abc', [1, 2], {'a': 1}` |

**Note**: 
- **Object** in pandas is a general data type that can store strings or mixed types (like lists, dictionaries).
------

**df.columns** provides you the names of columns along with the datatype of column names. Now, here the datatype given is 'object'.

### **What does object really means?**

Here object datatype can stand for anything like String, list, tuple, dictionary, etc.

### **What if we want to look at the datatype of each column?**

We can do so by using two attributes **DataFrame.dtypes** and **DataFrame.Series.dtype**. The basic difference between two is dtype provides you the datatype of mentioned column name in place of Series and dtypes provides you datatype of total columns. With DataFrame we mean the DataFrame reference we assigned **i.e. df** in our case.

In [52]:
df.dtypes

star_rating       float64
title              object
content_rating     object
genre              object
duration            int64
actors_list        object
dtype: object

In [56]:
df.duration

0      142
1      175
2      200
3      152
4      154
      ... 
974    116
975    118
976    138
977    114
978    126
Name: duration, Length: 979, dtype: int64

Here we are, as you can see now the datatype of each column and can make a conclusion by referencing to the dtype of actors_list that object datatype can also stand for list. It won't always stand for String or in simple words for text.


In [59]:
# to see datatype of particular column
df.duration.dtype
# this is the first way of writing this and with that I mean
# dataframe reference followed by series or column name by using period

dtype('int64')

In [60]:
# the second way of writing the same thing is by using the bracket notation. see below..
df["duration"].dtype

dtype('int64')

## **Indexing DataFrames**

There are several ways to index a Pandas DataFrame. One of the easiest ways to do this is by using square bracket notation.

In the example below, you can use square brackets to select one column of the DataFrame.

1. You can either use a single bracket or a double bracket.
2. The single bracket with output a Pandas Series, while a double bracket will output a Pandas DataFrame.


In [5]:
import pandas as pd

imdb = pd.read_csv("http://bit.ly/imdbratings")

# 'shape' attribute will give total number of rows and columns
print(imdb.shape)

(979, 6)


In [6]:
type(imdb["star_rating"]) 

pandas.core.series.Series

In [65]:
# you can mention the number of rows you want to see in head()
imdb["star_rating"].head(10)

0    9.3
1    9.2
2    9.1
3    9.0
4    8.9
5    8.9
6    8.9
7    8.9
8    8.9
9    8.9
Name: star_rating, dtype: float64

In [66]:
type(imdb[["star_rating", "genre"]])

pandas.core.frame.DataFrame

Square brackets can also be used to access observations (rows) from a DataFrame. For example:


In [68]:
# this will exclude 4 if you remember
imdb[555:560]

star_rating                 title content_rating      genre  duration  \
555          7.8          3:10 to Yuma              R  Adventure       122   
556          7.8  The Name of the Rose              R      Crime       130   
557          7.8          Mary Poppins       APPROVED     Comedy       139   
558          7.8              The Game              R      Drama       129   
559          7.8            Changeling              R      Drama       141   

                                           actors_list  
555  [u'Russell Crowe', u'Christian Bale', u'Ben Fo...  
556  [u'Sean Connery', u'Christian Slater', u'Helmu...  
557  [u'Julie Andrews', u'Dick Van Dyke', u'David T...  
558  [u'Michael Douglas', u'Deborah Kara Unger', u'...  
559    [u'Angelina Jolie', u'Colm Feore', u'Amy Ryan']

## **Pandas loc and iloc**

With **loc** and **iloc** you can do practically any data selection operation on DataFrames you can think of.

1. **loc** is label-based, which means that you have to specify rows and columns based on their row and column labels.
2. **iloc** is integer index based, so you have to specify rows and columns by their integer index.

Use this link for dataset http://bit.ly/drinksbycountry


In [13]:
import pandas as pd

# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data, index=['A', 'B', 'C'])

# Selecting row 'B' using loc
row_b = df.loc['B']
print(row_b)

Name            Bob
Age              30
City    Los Angeles
Name: B, dtype: object


In [14]:
# Selecting rows 'A' and 'C'
rows_ac = df.loc[['A', 'C']]
print(rows_ac)

      Name  Age      City
A    Alice   25  New York
C  Charlie   35   Chicago


In [15]:
# Selecting 'Name' and 'Age' for row 'B'
name_age_b = df.loc['B', ['Name', 'Age']]
name_age_b

Name    Bob
Age      30
Name: B, dtype: object

In [18]:
import pandas as pd

data = pd.read_csv("http://bit.ly/drinksbycountry")
data.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0      Asia  
1                           4.9    Europe  
2                           0.7    Africa  
3                          12.4    Europe  
4                           5.9    Africa

In [71]:
data.describe()

beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

In [12]:
# loc example
data.loc[1:10, ["country", "beer_servings", "continent"]]

country  beer_servings      continent
1             Albania             89         Europe
2             Algeria             25         Africa
3             Andorra            245         Europe
4              Angola            217         Africa
5   Antigua & Barbuda            102  North America
6           Argentina            193  South America
7             Armenia             21         Europe
8           Australia            261        Oceania
9             Austria            279         Europe
10         Azerbaijan             21         Europe

In [19]:
data.beer_servings >= 100 

0      False
1      False
2      False
3       True
4       True
       ...  
188     True
189     True
190    False
191    False
192    False
Name: beer_servings, Length: 193, dtype: bool

In [77]:
data.loc[data.beer_servings >= 100]

country  beer_servings  spirit_servings  wine_servings  \
3              Andorra            245              138            312   
4               Angola            217               57             45   
5    Antigua & Barbuda            102              128             45   
6            Argentina            193               25            221   
8            Australia            261               72            212   
..                 ...            ...              ...            ...   
182     United Kingdom            219              126            195   
184                USA            249              158             84   
185            Uruguay            115               35            220   
188          Venezuela            333              100              3   
189            Vietnam            111                2              1   

     total_litres_of_pure_alcohol      continent  
3                            12.4         Europe  
4                             5.9         Africa  
5                             4.9  North America  
6                             8.3  South America  
8                            10.4        Oceania  
..                            ...            ...  
182                          10.4         Europe  
184                           8.7  North America  
185                           6.6  South America  
188                           7.7  South America  
189                           2.0           Asia  

[79 rows x 6 columns]

In [20]:
# you can use loc with condition as well
a = data.loc[data.beer_servings >= 200].head(10)
a

country  beer_servings  spirit_servings  wine_servings  \
3     Andorra            245              138            312   
4      Angola            217               57             45   
8   Australia            261               72            212   
9     Austria            279               75            191   
16    Belgium            295               84            212   
17     Belize            263              114              8   
23     Brazil            245              145             16   
25   Bulgaria            231              252             94   
32     Canada            240              122            100   
42    Croatia            230               87            254   

    total_litres_of_pure_alcohol      continent  
3                           12.4         Europe  
4                            5.9         Africa  
8                           10.4        Oceania  
9                            9.7         Europe  
16                          10.5         Europe  
17                           6.8  North America  
23                           7.2  South America  
25                          10.3         Europe  
32                           8.2  North America  
42                          10.2         Europe

In [84]:
# you can access it with this way also
data.loc[data.country == "Argentina"]

country  beer_servings  spirit_servings  wine_servings  \
6  Argentina            193               25            221   

   total_litres_of_pure_alcohol      continent  
6                           8.3  South America

In [85]:
# iloc example
data.iloc[[1, 4, 7, 10, 12]]

country  beer_servings  spirit_servings  wine_servings  \
1      Albania             89              132             54   
4       Angola            217               57             45   
7      Armenia             21              179             11   
10  Azerbaijan             21               46              5   
12     Bahrain             42               63              7   

    total_litres_of_pure_alcohol continent  
1                            4.9    Europe  
4                            5.9    Africa  
7                            3.8    Europe  
10                           1.3    Europe  
12                           2.0      Asia

In [88]:
data.iloc[:4, :4]

country  beer_servings  spirit_servings  wine_servings
0  Afghanistan              0                0              0
1      Albania             89              132             54
2      Algeria             25                0             14
3      Andorra            245              138            312

## **Change the Column Headers**

Let us take the example of ratings dataset, where we will change the column header from “genre” to “movie_type”. So, let's implement it practically.


In [89]:
import pandas as pd

rate = pd.read_csv("http://bit.ly/imdbratings")
rate.head(10)

star_rating                                          title content_rating  \
0          9.3                       The Shawshank Redemption              R   
1          9.2                                  The Godfather              R   
2          9.1                         The Godfather: Part II              R   
3          9.0                                The Dark Knight          PG-13   
4          8.9                                   Pulp Fiction              R   
5          8.9                                   12 Angry Men      NOT RATED   
6          8.9                 The Good, the Bad and the Ugly      NOT RATED   
7          8.9  The Lord of the Rings: The Return of the King          PG-13   
8          8.9                               Schindler's List              R   
9          8.9                                     Fight Club              R   

       genre  duration                                        actors_list  
0      Crime       142  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      Crime       175    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2      Crime       200  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3     Action       152  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4      Crime       154  [u'John Travolta', u'Uma Thurman', u'Samuel L....  
5      Drama        96  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
6    Western       161  [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...  
7  Adventure       201  [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...  
8  Biography       195  [u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...  
9      Drama       139  [u'Brad Pitt', u'Edward Norton', u'Helena Bonh...

In [90]:
# rename() function allows you to rename column headers and value should be
# provided in the form of dictionary with old name as key

rate.rename(columns={"genre": "movie_type", "duration": "no_of_mins"}, inplace=True)
rate.head(6)

star_rating                     title content_rating movie_type  \
0          9.3  The Shawshank Redemption              R      Crime   
1          9.2             The Godfather              R      Crime   
2          9.1    The Godfather: Part II              R      Crime   
3          9.0           The Dark Knight          PG-13     Action   
4          8.9              Pulp Fiction              R      Crime   
5          8.9              12 Angry Men      NOT RATED      Drama   

   no_of_mins                                        actors_list  
0         142  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1         175    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2         200  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3         152  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4         154  [u'John Travolta', u'Uma Thurman', u'Samuel L....  
5          96  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...

After learning all this you might have some questions in your mind like how you can sort the dataframe, how can we access particular rows and columns based on certain conditions and performs arithmatic operations over the series.

Let's go through some of the questions to get concept of pandas a little bit more clear ...

## **Question 1: How do I remove a series or column from a data file?**

Use this link for dataset http://bit.ly/uforeports


In [91]:
import pandas as pd

ufo = pd.read_csv("http://bit.ly/uforeports", delimiter=',')
ufo.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [93]:
# this is important... If you are looking for a quick description of your dataframe
# you can use info() function
ufo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   City             18215 non-null  object
 1   Colors Reported  2882 non-null   object
 2   Shape Reported   15597 non-null  object
 3   State            18241 non-null  object
 4   Time             18241 non-null  object
dtypes: object(5)
memory usage: 712.7+ KB


In [94]:
ufo.describe()

City Colors Reported Shape Reported  State              Time
count     18215            2882          15597  18241             18241
unique     6475              27             27     52             16145
top     Seattle             RED          LIGHT     CA  11/16/1999 19:00
freq        187             780           2803   2529                27

In [95]:
# column name/names should be mentioned in the list and
# axis 1 is for columns and axis 0 is for rows
ufo.drop(["Colors Reported"], axis=1, inplace=True)
ufo.head(10)

City Shape Reported State              Time
0                Ithaca       TRIANGLE    NY    6/1/1930 22:00
1           Willingboro          OTHER    NJ   6/30/1930 20:00
2               Holyoke           OVAL    CO   2/15/1931 14:00
3               Abilene           DISK    KS    6/1/1931 13:00
4  New York Worlds Fair          LIGHT    NY   4/18/1933 19:00
5           Valley City           DISK    ND   9/15/1934 15:30
6           Crater Lake         CIRCLE    CA    6/15/1935 0:00
7                  Alma           DISK    MI    7/15/1936 0:00
8               Eklutna          CIGAR    AK  10/15/1936 17:00
9               Hubbard       CYLINDER    OR    6/15/1937 0:00

In [43]:
# instead of inplace = True you can assign also
ufo.drop(["City", "State"], axis=1, inplace=True)
ufo.head()

Shape Reported             Time
0       TRIANGLE   6/1/1930 22:00
1          OTHER  6/30/1930 20:00
2           OVAL  2/15/1931 14:00
3           DISK   6/1/1931 13:00
4          LIGHT  4/18/1933 19:00

In [98]:
# to delete rows you can assign row number or you can use compressed form of for loop
ufo.drop([x for x in range(2, 10)], axis=0, inplace=True)
ufo.head(15)

City Shape Reported State             Time
0        Ithaca       TRIANGLE    NY   6/1/1930 22:00
1   Willingboro          OTHER    NJ  6/30/1930 20:00
10      Fontana          LIGHT    CA  8/15/1937 21:00
11     Waterloo       FIREBALL    AL   6/1/1939 20:00
12       Belton         SPHERE    SC  6/30/1939 20:00
13       Keokuk           OVAL    IA    7/7/1939 2:00
14    Ludington           DISK    MI   6/1/1941 13:00
15  Forest Home         CIRCLE    CA   7/2/1941 11:30
16  Los Angeles            NaN    CA   2/25/1942 0:00
17    Hapeville            NaN    GA   6/1/1942 22:30
18       Oneida      RECTANGLE    TN   7/15/1942 1:00
19   Bering Sea          OTHER    AK  4/30/1943 23:00
20     Nebraska           DISK    NE   6/1/1943 15:00
21          NaN            NaN    LA   8/15/1943 0:00
22          NaN          LIGHT    LA   8/15/1943 0:00

## **Question 2: How do I sort a pandas dataframe or series?**


In [2]:
import pandas as pd

data = pd.read_csv("http://bit.ly/imdbratings")
data.head()

star_rating                     title content_rating   genre  duration  \
0          9.3  The Shawshank Redemption              R   Crime       142   
1          9.2             The Godfather              R   Crime       175   
2          9.1    The Godfather: Part II              R   Crime       200   
3          9.0           The Dark Knight          PG-13  Action       152   
4          8.9              Pulp Fiction              R   Crime       154   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4  [u'John Travolta', u'Uma Thurman', u'Samuel L....

In [104]:
# now suppose we want to sort 'title' series
x = data["duration"].sort_values(ascending=False)
x

476    242
157    238
78     229
142    224
445    220
      ... 
293     68
88      68
258     67
338     66
389     64
Name: duration, Length: 979, dtype: int64

In [4]:
# if you want to sort in decending order
x = data["title"].sort_values(ascending=False)
x.tail()

110    2001: A Space Odyssey
698                127 Hours
201         12 Years a Slave
5               12 Angry Men
542     (500) Days of Summer
Name: title, dtype: object

In [52]:
# but this is sorting a given series.
# what if we want to sort dataframe based on some column? ... see the code
data.sort_values(by="title", ascending=True, inplace=True)
data.head(10)

star_rating                  title content_rating      genre  duration  \
542          7.8   (500) Days of Summer          PG-13     Comedy        95   
5            8.9           12 Angry Men      NOT RATED      Drama        96   
201          8.1       12 Years a Slave              R  Biography       134   
698          7.6              127 Hours              R  Adventure        94   
110          8.3  2001: A Space Odyssey              G    Mystery       160   
910          7.5                   2046              R      Drama       129   
596          7.7               21 Grams              R      Crime       124   
624          7.7              25th Hour              R      Crime       135   
708          7.6       28 Days Later...              R     Horror       113   
60           8.5               3 Idiots          PG-13     Comedy       170   

                                           actors_list  
542  [u'Zooey Deschanel', u'Joseph Gordon-Levitt', ...  
5    [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
201  [u'Chiwetel Ejiofor', u'Michael Kenneth Willia...  
698  [u'James Franco', u'Amber Tamblyn', u'Kate Mara']  
110  [u'Keir Dullea', u'Gary Lockwood', u'William S...  
910  [u'Tony Chiu Wai Leung', u'Ziyi Zhang', u'Faye...  
596  [u'Sean Penn', u'Benicio Del Toro', u'Naomi Wa...  
624  [u'Edward Norton', u'Barry Pepper', u'Philip S...  
708  [u'Cillian Murphy', u'Naomie Harris', u'Christ...  
60         [u'Aamir Khan', u'Madhavan', u'Mona Singh']

In [6]:
# to sort data with reference to multiple series we will write
# see the output carefully and conclude the result

x = data.sort_values(["star_rating", "duration", "genre"])
x.head(10)

star_rating                 title content_rating      genre  duration  \
938          7.4   Alice in Wonderland              G  Animation        75   
948          7.4            Frances Ha              R     Comedy        86   
966          7.4    The Simpsons Movie          PG-13  Animation        87   
947          7.4            Eraserhead        UNRATED      Drama        89   
971          7.4    Death at a Funeral              R     Comedy        90   
933          7.4           Beetlejuice             PG     Comedy        92   
942          7.4       Raising Arizona          PG-13     Comedy        94   
959          7.4  Deconstructing Harry              R     Comedy        96   
943          7.4       The Bucket List          PG-13  Adventure        97   
939          7.4        Predestination              R      Drama        97   

                                           actors_list  
938  [u'Kathryn Beaumont', u'Ed Wynn', u'Richard Ha...  
948  [u'Greta Gerwig', u'Mickey Sumner', u'Adam Dri...  
966  [u'Dan Castellaneta', u'Julie Kavner', u'Nancy...  
947  [u'Jack Nance', u'Charlotte Stewart', u'Allen ...  
971  [u'Matthew Macfadyen', u'Peter Dinklage', u'Ew...  
933  [u'Alec Baldwin', u'Geena Davis', u'Michael Ke...  
942  [u'Nicolas Cage', u'Holly Hunter', u'Trey Wils...  
959  [u'Woody Allen', u'Judy Davis', u'Julia Louis-...  
943  [u'Jack Nicholson', u'Morgan Freeman', u'Sean ...  
939   [u'Ethan Hawke', u'Sarah Snook', u'Noah Taylor']

**Conclusion:** first it will get sort according to star_rating and then duration.


## **Question 3: How do I filter dataset from series values?**


In [106]:
import pandas as pd

movies = pd.read_csv("http://bit.ly/imdbratings")
movies.head(10)

star_rating                                          title content_rating  \
0          9.3                       The Shawshank Redemption              R   
1          9.2                                  The Godfather              R   
2          9.1                         The Godfather: Part II              R   
3          9.0                                The Dark Knight          PG-13   
4          8.9                                   Pulp Fiction              R   
5          8.9                                   12 Angry Men      NOT RATED   
6          8.9                 The Good, the Bad and the Ugly      NOT RATED   
7          8.9  The Lord of the Rings: The Return of the King          PG-13   
8          8.9                               Schindler's List              R   
9          8.9                                     Fight Club              R   

       genre  duration                                        actors_list  
0      Crime       142  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      Crime       175    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2      Crime       200  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3     Action       152  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4      Crime       154  [u'John Travolta', u'Uma Thurman', u'Samuel L....  
5      Drama        96  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
6    Western       161  [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...  
7  Adventure       201  [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...  
8  Biography       195  [u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...  
9      Drama       139  [u'Brad Pitt', u'Edward Norton', u'Helena Bonh...

In [107]:
# now we are going to filter out datset according to the duration for greater than or equal to 200
# this will give us a series of booleans with condition checked mentioned
booleans = movies.duration >= 200
booleans.head()

0    False
1    False
2     True
3    False
4    False
Name: duration, dtype: bool

In [108]:
# with the following code we can filter data with the help of booleans series
movies[movies.genre == "Crime"].head(10)

star_rating                     title content_rating  genre  duration  \
0           9.3  The Shawshank Redemption              R  Crime       142   
1           9.2             The Godfather              R  Crime       175   
2           9.1    The Godfather: Part II              R  Crime       200   
4           8.9              Pulp Fiction              R  Crime       154   
21          8.7               City of God              R  Crime       130   
23          8.7        The Usual Suspects              R  Crime       106   
28          8.6    Leon: The Professional              R  Crime       110   
34          8.6        American History X              R  Crime       119   
40          8.5            The Green Mile              R  Crime       189   
49          8.5              The Departed              R  Crime       151   

                                          actors_list  
0   [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1     [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2   [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
4   [u'John Travolta', u'Uma Thurman', u'Samuel L....  
21  [u'Alexandre Rodrigues', u'Matheus Nachtergael...  
23  [u'Kevin Spacey', u'Gabriel Byrne', u'Chazz Pa...  
28  [u'Jean Reno', u'Gary Oldman', u'Natalie Portm...  
34  [u'Edward Norton', u'Edward Furlong', u"Beverl...  
40  [u'Tom Hanks', u'Michael Clarke Duncan', u'Dav...  
49  [u'Leonardo DiCaprio', u'Matt Damon', u'Jack N...

In [109]:
# in more compressed form you can write it as
movies[movies.duration >= 200].head()

star_rating                                          title content_rating  \
2           9.1                         The Godfather: Part II              R   
7           8.9  The Lord of the Rings: The Return of the King          PG-13   
17          8.7                                  Seven Samurai        UNRATED   
78          8.4                    Once Upon a Time in America              R   
85          8.4                             Lawrence of Arabia             PG   

        genre  duration                                        actors_list  
2       Crime       200  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
7   Adventure       201  [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...  
17      Drama       207  [u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K...  
78      Crime       229  [u'Robert De Niro', u'James Woods', u'Elizabet...  
85  Adventure       216  [u"Peter O'Toole", u'Alec Guinness', u'Anthony...

In [110]:
# to filter it with reference to two or more series conditions we can write
# don't forget to use parenthesis so the compiler won't mismatch the conditions {probably}
movies[(movies.duration >= 200) & (movies.genre == "Drama")]

star_rating               title content_rating  genre  duration  \
17           8.7       Seven Samurai        UNRATED  Drama       207   
157          8.2  Gone with the Wind              G  Drama       238   
476          7.8              Hamlet          PG-13  Drama       242   

                                           actors_list  
17   [u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K...  
157  [u'Clark Gable', u'Vivien Leigh', u'Thomas Mit...  
476  [u'Kenneth Branagh', u'Julie Christie', u'Dere...

## **Question 4: How do I use string methods in pandas?**

Use this link for dataset http://bit.ly/chiporders


In [116]:
import pandas as pd

# now we are having tab seperated dataset that's why we are using read_table()
chip = pd.read_table("http://bit.ly/chiporders")
chip.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [117]:
chip.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [118]:
# above dataset is tab sepearted so instead of using read_table we can use read_csv
# but now we'll have to pass an additional parameter i.e. sep or delimiter

chip = pd.read_csv("http://bit.ly/chiporders", delimiter="\t")
chip.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [119]:
chip.item_name.str

In [120]:
# now suppose we want to upper (capatilize) every entry of item_name
# by default it's a series so to make compiler understand to compare
# it with string we will use 'str' keyword
# see the practical implementation below

chip.item_name.str.upper().head(10)

0             CHIPS AND FRESH TOMATO SALSA
1                                     IZZE
2                         NANTUCKET NECTAR
3    CHIPS AND TOMATILLO-GREEN CHILI SALSA
4                             CHICKEN BOWL
5                             CHICKEN BOWL
6                            SIDE OF CHIPS
7                            STEAK BURRITO
8                         STEAK SOFT TACOS
9                            STEAK BURRITO
Name: item_name, dtype: object

In [122]:
# let's search for Chicken word in each entry
chip.item_name.str.contains("Chicken").head(10)

0    False
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8    False
9    False
Name: item_name, dtype: bool

In [123]:
# to replace some entries you can use this
# and all string methods you know you can use

chip.item_name = chip.item_name.str.replace("Chicken Bowl", "Veg Biryani")
chip.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                            Veg Biryani   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

## **Question 5: How do I change the data types of Pandas series?**


In [8]:
import pandas as pd

drinks = pd.read_csv("http://bit.ly/drinksbycountry")
drinks.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0      Asia  
1                           4.9    Europe  
2                           0.7    Africa  
3                          12.4    Europe  
4                           5.9    Africa

In [125]:
drinks.describe()

beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

In [126]:
# let's see the dataypes of all series
drinks.dtypes

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [9]:
# suppose we want to change datatype of beer_servings to float
drinks.beer_servings = drinks.beer_servings.astype("int8", copy=False) 
# in astype() function instead of inplace we hae copy parameter
drinks.dtypes

country                          object
beer_servings                      int8
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [130]:
drinks.head(10)

country  beer_servings  spirit_servings  wine_servings  \
0        Afghanistan            0.0                0              0   
1            Albania           89.0              132             54   
2            Algeria           25.0                0             14   
3            Andorra          245.0              138            312   
4             Angola          217.0               57             45   
5  Antigua & Barbuda          102.0              128             45   
6          Argentina          193.0               25            221   
7            Armenia           21.0              179             11   
8          Australia          261.0               72            212   
9            Austria          279.0               75            191   

   total_litres_of_pure_alcohol      continent  
0                           0.0           Asia  
1                           4.9         Europe  
2                           0.7         Africa  
3                          12.4         Europe  
4                           5.9         Africa  
5                           4.9  North America  
6                           8.3  South America  
7                           3.8         Europe  
8                          10.4        Oceania  
9                           9.7         Europe

In [131]:
drinks = drinks.astype(
    {"beer_servings": "float32", "spirit_servings": "int32"}, copy=False
)
drinks.dtypes

country                          object
beer_servings                   float32
spirit_servings                   int32
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [81]:
# before actually reading the data you can modify the datatype
# have a look

pd.read_csv("http://bit.ly/drinksbycountry", dtype={"beer_servings": "float32"}).dtypes

country                          object
beer_servings                   float32
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

## **Question 6: How can I find missing values in the dataframe and deal with that?**


In [1]:
import pandas as pd

df = pd.read_csv("http://bit.ly/uforeports")
df.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [133]:
# have a look to the dataframe
df.shape

(18241, 5)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   City             18215 non-null  object
 1   Colors Reported  2882 non-null   object
 2   Shape Reported   15597 non-null  object
 3   State            18241 non-null  object
 4   Time             18241 non-null  object
dtypes: object(5)
memory usage: 712.7+ KB


If you can see there are all total 18241 entries and there are some missing values in colors Reported, shape Reported and City.


In [137]:
df.isna()

City  Colors Reported  Shape Reported  State   Time
0      False             True           False  False  False
1      False             True           False  False  False
2      False             True           False  False  False
3      False             True           False  False  False
4      False             True           False  False  False
...      ...              ...             ...    ...    ...
18236  False             True           False  False  False
18237  False             True           False  False  False
18238  False             True            True  False  False
18239  False            False           False  False  False
18240  False             True           False  False  False

[18241 rows x 5 columns]

In [13]:
# this is how isna() function works by giving true for missing values
# so by counting the number of true's we can have total number of missing values
# BASICALLY True = 1 and False = 0 so 0+1 = 1

df.isna().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64

In [139]:
# to count non-missing values
# makes no sense you can use info()
df.notna().sum()

City               18215
Colors Reported     2882
Shape Reported     15597
State              18241
Time               18241
dtype: int64

In [141]:
# to fill some value in place of missing values you can go for
# fillna() function
df.fillna(value="ravi").head(10)

City Colors Reported Shape Reported State              Time
0                Ithaca            ravi       TRIANGLE    NY    6/1/1930 22:00
1           Willingboro            ravi          OTHER    NJ   6/30/1930 20:00
2               Holyoke            ravi           OVAL    CO   2/15/1931 14:00
3               Abilene            ravi           DISK    KS    6/1/1931 13:00
4  New York Worlds Fair            ravi          LIGHT    NY   4/18/1933 19:00
5           Valley City            ravi           DISK    ND   9/15/1934 15:30
6           Crater Lake            ravi         CIRCLE    CA    6/15/1935 0:00
7                  Alma            ravi           DISK    MI    7/15/1936 0:00
8               Eklutna            ravi          CIGAR    AK  10/15/1936 17:00
9               Hubbard            ravi       CYLINDER    OR    6/15/1937 0:00

In [14]:
# to fill values of particular column
df.City.fillna(value="ravi", inplace=True)

C:\Users\AUM PATEL\AppData\Local\Temp\ipykernel_22200\4172537012.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.City.fillna(value="ravi", inplace=True)


In [7]:
df.isna().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64

In [144]:
df.head(10)

City Colors Reported Shape Reported State              Time
0                Ithaca             NaN       TRIANGLE    NY    6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ   6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO   2/15/1931 14:00
3               Abilene             NaN           DISK    KS    6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY   4/18/1933 19:00
5           Valley City             NaN           DISK    ND   9/15/1934 15:30
6           Crater Lake             NaN         CIRCLE    CA    6/15/1935 0:00
7                  Alma             NaN           DISK    MI    7/15/1936 0:00
8               Eklutna             NaN          CIGAR    AK  10/15/1936 17:00
9               Hubbard             NaN       CYLINDER    OR    6/15/1937 0:00

In [15]:
# let's see our dataframe with city UNkNOWn
df[df.City == "ravi"].head(10)

City Colors Reported Shape Reported State              Time
21    ravi             NaN            NaN    LA    8/15/1943 0:00
22    ravi             NaN          LIGHT    LA    8/15/1943 0:00
204   ravi             NaN           DISK    CA   7/15/1952 12:30
241   ravi            BLUE           DISK    MT    7/4/1953 14:00
613   ravi             NaN           DISK    NV    7/1/1960 12:00
1877  ravi          YELLOW         CIRCLE    AZ    8/15/1969 1:00
2013  ravi             NaN            NaN    NH     8/1/1970 9:30
2546  ravi             NaN       FIREBALL    OH  10/25/1973 23:30
3123  ravi             RED       TRIANGLE    WV  11/25/1975 23:00
4736  ravi             NaN         SPHERE    CA   6/23/1982 23:00

In [149]:
# to drop/delete missing values
# * 'any' : If any NA values are present, drop that row or column.
# * 'all' : If all values are NA, drop that row or column.
df.dropna(how="any", inplace=False, axis=0).shape

(2486, 5)

In [46]:
df.dropna(how="all", axis=1).head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

Let's now move towards some of the most useful general pandas functions


## **Python | Pandas.melt()**

To make analysis of data in table easier, we can reshape the data into a more computer-friendly form using Pandas in Python. Pandas.melt() is one of the function to do so..

**Pandas.melt()** unpivots a DataFrame from wide format to long format.
melt() function is useful to massage a DataFrame into a format where one or more columns are **identifier variables**, while all other columns, considered **measured variables**, are **unpivoted** to the row axis, leaving just two non-identifier columns, variable and value.

**Syntax :**

```
pandas.melt(frame: pandas.core.frame.DataFrame, id_vars=None, value_vars=None, var_name=None, value_name='value', col_level=None)

**Parameters**

id_vars: tuple, list, or ndarray, optional
- Column(s) to use as identifier variables.

value_vars: tuple, list, or ndarray, optional
- Column(s) to unpivot. If not specified, uses all columns that are not set as id_vars.

var_name: scalar
- Name to use for the ‘variable’ column. If None it uses frame.columns.name or ‘variable’.

value_name: scalar, default ‘value’
- Name to use for the ‘value’ column.

col_level: int or str, optional
- If columns are a MultiIndex then use this level to melt.
```


In [91]:
import pandas as pd

df = pd.DataFrame(
    {
        "area": [1200, 1522, 1458, 2578, 5685, 5845, 5987, 4548],
        "mumbai_price": [11, 22, 12, 45, 77, 85, 47, 95],
        "pune_price": [14, 15, 36, 42, 56, 56, 36, 35],
        "raigad_price": [78, 56, 56, 56, 58, 32, 56, 33],
    }
)
df

area  mumbai_price  pune_price  raigad_price
0  1200            11          14            78
1  1522            22          15            56
2  1458            12          36            56
3  2578            45          42            56
4  5685            77          56            58
5  5845            85          56            32
6  5987            47          36            56
7  4548            95          35            33

In [24]:
pd.melt(df)

variable  value
0           area   1200
1           area   1522
2           area   1458
3           area   2578
4           area   5685
5           area   5845
6           area   5987
7           area   4548
8   mumbai_price     11
9   mumbai_price     22
10  mumbai_price     12
11  mumbai_price     45
12  mumbai_price     77
13  mumbai_price     85
14  mumbai_price     47
15  mumbai_price     95
16    pune_price     14
17    pune_price     15
18    pune_price     36
19    pune_price     42
20    pune_price     56
21    pune_price     56
22    pune_price     36
23    pune_price     35
24  raigad_price     78
25  raigad_price     56
26  raigad_price     56
27  raigad_price     56
28  raigad_price     58
29  raigad_price     32
30  raigad_price     56
31  raigad_price     33

As you can see it's taking columns as variables and their values as values. In simple words melt() function is categorizing or we can say unpivoting the datafrme according to columns. We can make the function to select a particular or more than one column to be considered as a variable.

Have a look..


In [25]:
df.columns

Index(['area', 'mumbai_price', 'pune_price', 'raigad_price'], dtype='object')

In [26]:
pd.melt(df, id_vars=["area"], value_vars=["mumbai_price", "pune_price", "raigad_price"])

area      variable  value
0   1200  mumbai_price     11
1   1522  mumbai_price     22
2   1458  mumbai_price     12
3   2578  mumbai_price     45
4   5685  mumbai_price     77
5   5845  mumbai_price     85
6   5987  mumbai_price     47
7   4548  mumbai_price     95
8   1200    pune_price     14
9   1522    pune_price     15
10  1458    pune_price     36
11  2578    pune_price     42
12  5685    pune_price     56
13  5845    pune_price     56
14  5987    pune_price     36
15  4548    pune_price     35
16  1200  raigad_price     78
17  1522  raigad_price     56
18  1458  raigad_price     56
19  2578  raigad_price     56
20  5685  raigad_price     58
21  5845  raigad_price     32
22  5987  raigad_price     56
23  4548  raigad_price     33

In [6]:
pd.melt(df,id_vars=["pune_price","area"]) 

pune_price  area      variable  value
0           14  1200  mumbai_price     11
1           15  1522  mumbai_price     22
2           36  1458  mumbai_price     12
3           42  2578  mumbai_price     45
4           56  5685  mumbai_price     77
5           56  5845  mumbai_price     85
6           36  5987  mumbai_price     47
7           35  4548  mumbai_price     95
8           14  1200  raigad_price     78
9           15  1522  raigad_price     56
10          36  1458  raigad_price     56
11          42  2578  raigad_price     56
12          56  5685  raigad_price     58
13          56  5845  raigad_price     32
14          36  5987  raigad_price     56
15          35  4548  raigad_price     33

now i think we can relate this....

The function is keeping area column constant for every other column mentioned in value_vars parameter and showing results in the form of price realated to columns mentioned in value_vars. So we can say the function is kind of melting the dataframe or we can say it's just unpivoting the dataframe which might be having some use in real life.


In [27]:
# you can give the name you want to give to your variable and value column just created
# let's assign the unpivoted dataframe to our original dataframe reference

df = pd.melt(
    df,
    id_vars=["area"],
    value_vars=["mumbai_price", "pune_price", "raigad_price"],
    var_name="region",
    value_name="rs in LAKHS",
)
df

area        region  rs in LAKHS
0   1200  mumbai_price           11
1   1522  mumbai_price           22
2   1458  mumbai_price           12
3   2578  mumbai_price           45
4   5685  mumbai_price           77
5   5845  mumbai_price           85
6   5987  mumbai_price           47
7   4548  mumbai_price           95
8   1200    pune_price           14
9   1522    pune_price           15
10  1458    pune_price           36
11  2578    pune_price           42
12  5685    pune_price           56
13  5845    pune_price           56
14  5987    pune_price           36
15  4548    pune_price           35
16  1200  raigad_price           78
17  1522  raigad_price           56
18  1458  raigad_price           56
19  2578  raigad_price           56
20  5685  raigad_price           58
21  5845  raigad_price           32
22  5987  raigad_price           56
23  4548  raigad_price           33

## **PANDAS PIVOT**

Most people likely have experience with pivot tables in Excel. Pandas provides a similar function called (appropriately enough) pivot_table . Reshape data (produce a “pivot” table) based on column values. Uses unique values from specified index / columns to form axes of the resulting DataFrame. This function does not support data aggregation, multiple values will result in a MultiIndex in the columns.

**Syntax:**

```
pandas.pivot(data: ‘DataFrame’, index=None, columns=None, values=None)

**Parameters**

data: DataFrame

index: str or object, optional
- Column to use to make new frame’s index. If None, uses existing index.

columns: str or object
- Column to use to make new frame’s columns.

values: str, object or a list of the previous, optional
- Column(s) to use for populating new frame’s values. If not specified, all remaining columns will be used and the result will have hierarchically indexed columns.

**Returns**

DataFrame
Returns reshaped DataFrame.

**Raises**

ValueError:
When there are any index, columns combinations with multiple values. DataFrame.pivot_table when you need to aggregate.
```


In [98]:
import pandas as pd

df = pd.DataFrame(
    {
        "area": [1200, 1522, 1458, 2578, 5685, 5845, 5987, 4548],
        "mumbai_price": [11, 22, 12, 45, 77, 85, 47, 95],
        "pune_price": [14, 15, 36, 42, 56, 56, 36, 35],
        "raigad_price": [78, 56, 56, 56, 58, 32, 56, 33],
    }
)
df

area  mumbai_price  pune_price  raigad_price
0  1200            11          14            78
1  1522            22          15            56
2  1458            12          36            56
3  2578            45          42            56
4  5685            77          56            58
5  5845            85          56            32
6  5987            47          36            56
7  4548            95          35            33

In [96]:
import pandas as pd

pd.pivot(df, columns="area", index="pune_price", values=["mumbai_price"]).head()
# try to find a conclusion for this function
# at index pune_price(14) ,column area(1200) the value is 11.0


mumbai_price                                        
area               1200  1458  1522  2578  4548 5685 5845  5987
pune_price                                                     
14                 11.0   NaN   NaN   NaN   NaN  NaN  NaN   NaN
15                  NaN   NaN  22.0   NaN   NaN  NaN  NaN   NaN
35                  NaN   NaN   NaN   NaN  95.0  NaN  NaN   NaN
36                  NaN  12.0   NaN   NaN   NaN  NaN  NaN  47.0
42                  NaN   NaN   NaN  45.0   NaN  NaN  NaN   NaN

In [104]:
df[df["area"] == 1200]

area  mumbai_price  pune_price  raigad_price
0  1200            11          14            78

In [97]:
pd.pivot(df, columns="area", index="pune_price", values=["raigad_price"]).head()

raigad_price                                        
area               1200  1458  1522  2578  4548 5685 5845  5987
pune_price                                                     
14                 78.0   NaN   NaN   NaN   NaN  NaN  NaN   NaN
15                  NaN   NaN  56.0   NaN   NaN  NaN  NaN   NaN
35                  NaN   NaN   NaN   NaN  33.0  NaN  NaN   NaN
36                  NaN  56.0   NaN   NaN   NaN  NaN  NaN  56.0
42                  NaN   NaN   NaN  56.0   NaN  NaN  NaN   NaN

In short its taking region column values as new columns and as we are assigning values to be 'rs in lakhs' this column, every new column will have it's seperate value now. In more simple words we have pivoted our unpivoted dataframe.

Let's explore something more with real data....


In [32]:
import pandas as pd

df = pd.read_csv("http://bit.ly/drinksbycountry")
df.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0      Asia  
1                           4.9    Europe  
2                           0.7    Africa  
3                          12.4    Europe  
4                           5.9    Africa

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   country                       193 non-null    object 
 1   beer_servings                 193 non-null    int64  
 2   spirit_servings               193 non-null    int64  
 3   wine_servings                 193 non-null    int64  
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     193 non-null    object 
dtypes: float64(1), int64(3), object(2)
memory usage: 9.2+ KB


In [34]:
# now we are going to look at a very very important function and that is nothing but
# describe(). see what it does..

df.describe()

beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

As you can see it shows some of the mathematical representation of our numerical columns and you guys need to get this by your own.


In [35]:
# let's see how many continents do we have
"""
well it's not possible to look into whole dataframe just to count continents. Don't worry
pandas is having functions called as unique() and nunique() which will do this task for us.
see Below ...
"""

df.continent.unique()

array(['Asia', 'Europe', 'Africa', 'North America', 'South America',
       'Oceania'], dtype=object)

In [36]:
# so we have above continents and using nunique() you will get
df.continent.nunique()
# total 6 continents

6

In [37]:
# NOTE: we have one more function that performs the same task but in more efficient way
# i.e. value_counts()

df.continent.value_counts()

continent
Africa           53
Europe           45
Asia             44
North America    23
Oceania          16
South America    12
Name: count, dtype: int64

Basically it's giving you the number of unique continents, total number of times they have entries in dataframe like africa 53. That's how i personally recommend this for future examples...


## **PANDAS PIVOT TABLE**

Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects (hierarchical indexes) on the index and columns of the result DataFrame.

**Syntax:**

```
pandas.pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All', observed=False)

```


In [109]:
df = pd.DataFrame(
    {
        "A": ["foo", "foo", "foo", "foo", "foo", "bar", "bar", "bar", "bar"],
        "B": ["one", "one", "one", "two", "two", "one", "one", "two", "two"],
        "C": [
            "small",
            "large",
            "large",
            "small",
            "medium",
            "large",
            "small",
            "small",
            "large",
        ],
        "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
        "E": [2, 4, 5, 5, 6, 6, 8, 9, 9],
    }
)
df

A    B       C  D  E
0  foo  one   small  1  2
1  foo  one   large  2  4
2  foo  one   large  2  5
3  foo  two   small  3  5
4  foo  two  medium  3  6
5  bar  one   large  4  6
6  bar  one   small  5  8
7  bar  two   small  6  9
8  bar  two   large  7  9

In [110]:
import numpy as np

pd.pivot_table(df, values="D", index=["A", "B"], columns=["C"], aggfunc=np.sum)

C:\Users\AUM PATEL\AppData\Local\Temp\ipykernel_14156\3846333675.py:3: FutureWarning: The provided callable <function sum at 0x0000017364BBC180> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df, values="D", index=["A", "B"], columns=["C"], aggfunc=np.sum)


C        large  medium  small
A   B                        
bar one    4.0     NaN    5.0
    two    7.0     NaN    6.0
foo one    4.0     NaN    1.0
    two    NaN     3.0    3.0

## **PANDAS GROUPBY**

Any groupby operation involves one of the following operations on the original object. They are −

- Splitting the Object

- Applying a function

- Combining the results

In many situations, we split the data into sets and we apply some functionality on each subset. In the apply functionality, we can perform the following operations −

- Aggregation − computing a summary statistic

- Transformation − perform some group-specific operation

- Filtration − discarding the data with some condition

**Syntax:**

```
DataFrame.groupby(self, by=None, axis=0, level=None, as_index: bool = True, sort: bool = True, group_keys: bool = True, squeeze: bool = False, observed: bool = False)
```


In [40]:
import pandas as pd

df = pd.read_csv("http://bit.ly/drinksbycountry")
df.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0      Asia  
1                           4.9    Europe  
2                           0.7    Africa  
3                          12.4    Europe  
4                           5.9    Africa

In [41]:
# as per the definition of groupby() function, first of all it splits the dataframe
# for the provided column name as parameter. After that it pefrorms the operation menntioned
# with the function and it combines the result and shows us in the form of dataframe.

# Note: We can't say it returns the dataframe but we can say it returns dataframe_groupby.
# think about it a little..

df.groupby("continent").count()

country  beer_servings  spirit_servings  wine_servings  \
continent                                                               
Africa              53             53               53             53   
Asia                44             44               44             44   
Europe              45             45               45             45   
North America       23             23               23             23   
Oceania             16             16               16             16   
South America       12             12               12             12   

               total_litres_of_pure_alcohol  
continent                                    
Africa                                   53  
Asia                                     44  
Europe                                   45  
North America                            23  
Oceania                                  16  
South America                            12

In [42]:
df2 = df.iloc[:, 1:]
df2.groupby("continent").mean()

beer_servings  spirit_servings  wine_servings  \
continent                                                      
Africa             61.471698        16.339623      16.264151   
Asia               37.045455        60.840909       9.068182   
Europe            193.777778       132.555556     142.222222   
North America     145.434783       165.739130      24.521739   
Oceania            89.687500        58.437500      35.625000   
South America     175.083333       114.750000      62.416667   

               total_litres_of_pure_alcohol  
continent                                    
Africa                             3.007547  
Asia                               2.170455  
Europe                             8.617778  
North America                      5.995652  
Oceania                            3.381250  
South America                      6.308333

As you can see above first of all our dataframe got split into different continets and then mean operation performed by the function on splitted dataframe after which function combined the splitted dataframe to give us dataframe_groupby.


In [43]:
# we can do this for single column / series too
df.groupby("continent").beer_servings.mean()

continent
Africa            61.471698
Asia              37.045455
Europe           193.777778
North America    145.434783
Oceania           89.687500
South America    175.083333
Name: beer_servings, dtype: float64

In [44]:
# let's check whether its working or not

# first we will filter our dataframe just for Africa
df[df.continent == "Africa"].head()

country  beer_servings  spirit_servings  wine_servings  \
2        Algeria             25                0             14   
4         Angola            217               57             45   
18         Benin             34                4             13   
22      Botswana            173               35             35   
26  Burkina Faso             25                7              7   

    total_litres_of_pure_alcohol continent  
2                            0.7    Africa  
4                            5.9    Africa  
18                           1.1    Africa  
22                           5.4    Africa  
26                           4.3    Africa

In [45]:
# ok now we will perform operation for beer_servings
# as i am not taking any reference i'll have to rewrite above code

df[df.continent == "Africa"].beer_servings.mean()
# is it giving me the same ans we got with groupby?

np.float64(61.471698113207545)

In [46]:
# what if you want to perform different operations like mean?
# well you can with the help of agg() function

df.iloc[:, 1:].groupby("continent").agg(["mean", "max", "min", "std"])

beer_servings                     spirit_servings           \
                       mean  max min        std            mean  max min   
continent                                                                  
Africa            61.471698  376   0  80.557816       16.339623  152   0   
Asia              37.045455  247   0  49.469725       60.840909  326   0   
Europe           193.777778  361   0  99.631569      132.555556  373   0   
North America    145.434783  285   1  79.621163      165.739130  438  68   
Oceania           89.687500  306   0  96.641412       58.437500  254   0   
South America    175.083333  333  93  65.242845      114.750000  302  25   

                         wine_servings                      \
                     std          mean  max min        std   
continent                                                    
Africa         28.102794     16.264151  233   0  38.846419   
Asia           84.362160      9.068182  123   0  21.667034   
Europe         77.589115    142.222222  370   0  97.421738   
North America  94.993884     24.521739  100   1  28.266378   
Oceania        70.504817     35.625000  212   0  64.555790   
South America  77.077440     62.416667  221   1  88.620189   

              total_litres_of_pure_alcohol                       
                                      mean   max  min       std  
continent                                                        
Africa                            3.007547   9.1  0.0  2.647557  
Asia                              2.170455  11.5  0.0  2.770239  
Europe                            8.617778  14.4  0.0  3.358455  
North America                     5.995652  11.9  2.2  2.409353  
Oceania                           3.381250  10.4  0.0  3.345688  
South America                     6.308333   8.3  3.8  1.531166

That's amazing right??? now go for something more by your own.


## **PANDAS CROSSTAB**

Compute a simple cross tabulation of two (or more) factors. By default computes a frequency table of the factors unless an array of values and an aggregation function are passed.

**SYNTAX:**

```
pandas.crosstab(index, columns, values=None, rownames=None, colnames=None, aggfunc=None, margins=False, margins_name: str = 'All', dropna: bool = True, normalize=False)
```

# `pd.crosstab` Function in Detail

`pandas.crosstab` is a versatile function that allows you to compute a simple cross-tabulation of two (or more) factors. This function is used to aggregate data based on the frequency of occurrence or for summarizing the relationship between multiple categorical variables.

## Basic Syntax

```python
pd.crosstab(index, columns, values=None, rownames=None, colnames=None, aggfunc=None, margins=False, margins_name='All', dropna=True, normalize=False)
```

### Parameters

- **`index`**: array-like, Series, or list of arrays/Series.
  - Values to group by in rows.
  
- **`columns`**: array-like, Series, or list of arrays/Series.
  - Values to group by in columns.
  
- **`values`**: array-like or Series, optional.
  - Values to aggregate. If provided, `aggfunc` is required.
  
- **`aggfunc`**: function, optional.
  - Aggregation function to apply if `values` is provided. Examples: `np.sum`, `np.mean`, `np.max`, etc.
  
- **`rownames`**: list of names, optional.
  - If specified, names of the rows in the result.
  
- **`colnames`**: list of names, optional.
  - If specified, names of the columns in the result.
  
- **`margins`**: bool, default `False`.
  - If `True`, adds row/column totals (margins).
  
- **`margins_name`**: str, default `'All'`.
  - Name of the row/column that will contain the totals.
  
- **`dropna`**: bool, default `True`.
  - If `True`, does not include columns whose entries are all `NaN`.
  
- **`normalize`**: bool, {‘all’, ‘index’, ‘columns’}, or False, default `False`.
  - Normalize the table across the dimension specified by `normalize`.

### Key Features

1. **Basic Cross-Tabulation:**

   This returns a frequency count table of combinations of two categorical variables:

   ```python
   pd.crosstab(df.Sex, df.Handedness)
   ```

2. **Using `aggfunc` for Aggregation:**

   You can aggregate numerical values using functions like `np.sum`, `np.mean`, etc.

   ```python
   pd.crosstab(df.Nationality, df.Handedness, values=df.Age, aggfunc=np.max)
   ```

3. **Adding Margins (Totals):**

   You can add totals to the rows and columns using the `margins=True` parameter.

   ```python
   pd.crosstab(df.Sex, df.Handedness, margins=True)
   ```

   This will give you the total counts for each combination.

4. **Normalization Options:**

   - `normalize="all"`: Normalizes the entire table, so all values sum to 1.
   - `normalize="index"`: Normalizes the values row-wise (across each row).
   - `normalize="columns"`: Normalizes the values column-wise (across each column).

   Example:

   ```python
   pd.crosstab(df.Sex, df.Handedness, normalize="index")
   ```

   This will give row-wise proportions.

5. **Drop `NaN` Columns:**

   By default, `dropna=True`, which means columns containing all `NaN` will be omitted from the result.

   ```python
   pd.crosstab(df.Sex, df.Handedness, dropna=False)
   ```

6. **Row and Column Names:**

   You can customize the row and column names in the resulting table using `rownames` and `colnames`.

   ```python
   pd.crosstab(df.Sex, df.Handedness, rownames=['Gender'], colnames=['Hand'])
   ```

## Conclusion

The `pd.crosstab` function is highly useful for generating summary tables that highlight the frequency or relationship between two categorical variables. By using the various options like `aggfunc`, `margins`, and `normalize`, you can tailor the output to fit your data analysis needs.



In [47]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [112]:
import pandas as pd

df = pd.DataFrame(
    {
        "Name": ["kathy", "linda", "peter", "john", "fatima", "kaval", "dhabir", "dev"],
        "Nationality": [
            "usa",
            "usa",
            "bangaladesh",
            "india",
            "india",
            "bangladesh",
            "usa",
            "india",
        ],
        "Sex": ["female", "female", "male", "male", "female", "female", "male", "male"],
        "Age": [15, 18, 14, 17, 15, 16, 19, 25],
        "Handedness": [
            "right",
            "left",
            "right",
            "left",
            "left",
            "right",
            "left",
            "right",
        ],
    }
)

df

Name  Nationality     Sex  Age Handedness
0   kathy          usa  female   15      right
1   linda          usa  female   18       left
2   peter  bangaladesh    male   14      right
3    john        india    male   17       left
4  fatima        india  female   15       left
5   kaval   bangladesh  female   16      right
6  dhabir          usa    male   19       left
7     dev        india    male   25      right

In [118]:
pd.crosstab(df.Nationality, df.Handedness)

Handedness   left  right
Nationality             
bangaladesh     0      1
bangladesh      0      1
india           2      1
usa             2      1

In [ ]:
pd.crosstab(df.Sex, df.Handedness,df.Age,aggfunc=np.max,margins=True)   
# margins operate on aggfunc if given or else adds up all 

C:\Users\AUM PATEL\AppData\Local\Temp\ipykernel_14156\1139958006.py:1: FutureWarning: The provided callable <function max at 0x0000017364BBCB80> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pd.crosstab(df.Sex, df.Handedness,df.Age,aggfunc=np.max,margins=True)
C:\Users\AUM PATEL\AppData\Local\Temp\ipykernel_14156\1139958006.py:1: FutureWarning: The provided callable <function max at 0x0000017364BBCB80> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pd.crosstab(df.Sex, df.Handedness,df.Age,aggfunc=np.max,margins=True)
C:\Users\AUM PATEL\AppData\Local\Temp\ipykernel_14156\1139958006.py:1: FutureWarning: The provided callable <function max at 0x0000017364BBCB80> is currently using DataFrameGroupBy.max. In a future version of pandas, the

Handedness  left  right  All
Sex                         
female        18     16   18
male          19     25   25
All           19     25   25

In [51]:
pd.crosstab(df.Sex, df.Handedness, margins=True)        # hmmm can be used for chi square test

Handedness  left  right  All
Sex                         
female         2      2    4
male           2      2    4
All            4      4    8

In [52]:
pd.crosstab(df.Sex, [df.Handedness, df.Nationality], margins=True)

Handedness   left           right                      All
Nationality india usa bangaladesh bangladesh india usa    
Sex                                                       
female          1   1           0          1     0   1   4
male            1   1           1          0     1   0   4
All             2   2           1          1     1   1   8

In [53]:
pd.crosstab([df.Nationality, df.Sex], [df.Handedness], margins=True)

Handedness          left  right  All
Nationality Sex                     
bangaladesh male       0      1    1
bangladesh  female     0      1    1
india       female     1      0    1
            male       1      1    2
usa         female     1      1    2
            male       1      0    1
All                    4      4    8

In [127]:
pd.crosstab(df.Sex, df.Handedness, normalize="index")

Handedness  left  right
Sex                    
female       0.5    0.5
male         0.5    0.5

In [55]:
import numpy as np

pd.crosstab(df.Sex, df.Handedness, values=df.Age, aggfunc=np.average)

Handedness  left  right
Sex                    
female      16.5   15.5
male        18.0   19.5

## **PANDAS TO DATETIME**

Convert argument to datetime.

**Syntax:**

```
pandas.to_datetime(arg, errors='raise', dayfirst=False, yearfirst=False, utc=None, format=None, exact=True, unit=None, infer_datetime_format=False, origin='unix', cache=True)
```

# ` HH:mm:ss , here capital HH means that it is a 24 hr clock `


In [56]:
import pandas as pd

df = pd.read_csv("http://bit.ly/uforeports")
df.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   City             18215 non-null  object
 1   Colors Reported  2882 non-null   object
 2   Shape Reported   15597 non-null  object
 3   State            18241 non-null  object
 4   Time             18241 non-null  object
dtypes: object(5)
memory usage: 712.7+ KB


In [58]:
pd.to_datetime(df.Time)
# YYYY-MM-DD HH:mm:ss

0       1930-06-01 22:00:00
1       1930-06-30 20:00:00
2       1931-02-15 14:00:00
3       1931-06-01 13:00:00
4       1933-04-18 19:00:00
                ...        
18236   2000-12-31 23:00:00
18237   2000-12-31 23:00:00
18238   2000-12-31 23:45:00
18239   2000-12-31 23:45:00
18240   2000-12-31 23:59:00
Name: Time, Length: 18241, dtype: datetime64[ns]

In [59]:
# let's see datatypes of each column
df.dtypes

City               object
Colors Reported    object
Shape Reported     object
State              object
Time               object
dtype: object

In [60]:
# did u see that? Its showing dtype object for time column which is irrelevant
# we have to convert it to proper date and time
# and pd.to_datetime() does the same

df["time_using_datetime"] = pd.to_datetime(df.Time)
df.head()

City Colors Reported Shape Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

  time_using_datetime  
0 1930-06-01 22:00:00  
1 1930-06-30 20:00:00  
2 1931-02-15 14:00:00  
3 1931-06-01 13:00:00  
4 1933-04-18 19:00:00

In [61]:
df.dtypes

City                           object
Colors Reported                object
Shape Reported                 object
State                          object
Time                           object
time_using_datetime    datetime64[ns]
dtype: object

In [62]:
df.time_using_datetime[0]

Timestamp('1930-06-01 22:00:00')

See the above code carefully. With that we are creating one more series in our dataframe and remember while creating series always use bracket notation.

now let's see dtypes again...


In [63]:
# as you can see now dtype 'datetime64[ns]'.
# like str it's having dt keyword reference we can say to access info
# see below


df.time_using_datetime.dt.date

0        1930-06-01
1        1930-06-30
2        1931-02-15
3        1931-06-01
4        1933-04-18
            ...    
18236    2000-12-31
18237    2000-12-31
18238    2000-12-31
18239    2000-12-31
18240    2000-12-31
Name: time_using_datetime, Length: 18241, dtype: object

In [64]:
df.time_using_datetime.dt.time

0        22:00:00
1        20:00:00
2        14:00:00
3        13:00:00
4        19:00:00
           ...   
18236    23:00:00
18237    23:00:00
18238    23:45:00
18239    23:45:00
18240    23:59:00
Name: time_using_datetime, Length: 18241, dtype: object

In [65]:
df.time_using_datetime.dt.hour

0        22
1        20
2        14
3        13
4        19
         ..
18236    23
18237    23
18238    23
18239    23
18240    23
Name: time_using_datetime, Length: 18241, dtype: int32

In [66]:
df.time_using_datetime.dt.month

0         6
1         6
2         2
3         6
4         4
         ..
18236    12
18237    12
18238    12
18239    12
18240    12
Name: time_using_datetime, Length: 18241, dtype: int32

And many more see documentation and find some more attributes for dt....


## **Pandas Dummy Variables**

**get_dummies() function**

The get_dummies() function is used to convert categorical variable into dummy/indicator variables. A dummy variable (aka, an indicator variable) is a numeric variable that represents categorical data, such as gender, race, political affiliation, etc.

**syntax:**

```
pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)
```

Use this link for dataset http://bit.ly/kaggletrain

In [129]:
data = pd.read_csv("http://bit.ly/kaggletrain")
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [130]:
# let's create dummy variable for every possible value in sex column
# and with that i mean we will assign some numeric value to every unique possible
# value of desired column

data["male_sex"] = data.Sex.map({"male": 1, "female": 0})
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  male_sex  
0      0         A/5 21171   7.2500   NaN        S         1  
1      0          PC 17599  71.2833   C85        C         0  
2      0  STON/O2. 3101282   7.9250   NaN        S         0  
3      0            113803  53.1000  C123        S         0  
4      0            373450   8.0500   NaN        S         1

In [69]:
# just focus on the last column we have assigned numeric values to male and female
# this task is very useful while designing your machine learning model
# because machine understands number not categorical values

# with get_dummies()

pd.get_dummies(data.Sex)

female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [132]:
# now it has created seperate column for male and female and that's the magic
# it's necessary to avoid "dummy varible trap". YOu will definitely learn about this ahead.

# let's rename those column names with prefix parameter

pd.get_dummies(data.Sex, prefix="sex")

sex_female  sex_male
0         False      True
1          True     False
2          True     False
3          True     False
4         False      True
..          ...       ...
886       False      True
887        True     False
888        True     False
889       False      True
890       False      True

[891 rows x 2 columns]

In [71]:
# now let's do it for other column as well 'Embarked'

data.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [72]:
pd.get_dummies(data.Embarked, prefix="class")

class_C  class_Q  class_S
0      False    False     True
1       True    False    False
2      False    False     True
3      False    False     True
4      False    False     True
..       ...      ...      ...
886    False    False     True
887    False    False     True
888    False    False     True
889     True    False    False
890    False     True    False

[891 rows x 3 columns]

In [73]:
# you can do this for entire dataframe as well
# for every categorical column it will perform it's operation

pd.get_dummies(data)

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  male_sex  \
0              1         0       3  22.0      1      0   7.2500         1   
1              2         1       1  38.0      1      0  71.2833         0   
2              3         1       3  26.0      0      0   7.9250         0   
3              4         1       1  35.0      1      0  53.1000         0   
4              5         0       3  35.0      0      0   8.0500         1   
..           ...       ...     ...   ...    ...    ...      ...       ...   
886          887         0       2  27.0      0      0  13.0000         1   
887          888         1       1  19.0      0      0  30.0000         0   
888          889         0       3   NaN      1      2  23.4500         0   
889          890         1       1  26.0      0      0  30.0000         1   
890          891         0       3  32.0      0      0   7.7500         1   

     Name_Abbing, Mr. Anthony  Name_Abbott, Mr. Rossmore Edward  ...  \
0                       False                             False  ...   
1                       False                             False  ...   
2                       False                             False  ...   
3                       False                             False  ...   
4                       False                             False  ...   
..                        ...                               ...  ...   
886                     False                             False  ...   
887                     False                             False  ...   
888                     False                             False  ...   
889                     False                             False  ...   
890                     False                             False  ...   

     Cabin_F G73  Cabin_F2  Cabin_F33  Cabin_F38  Cabin_F4  Cabin_G6  Cabin_T  \
0          False     False      False      False     False     False    False   
1          False     False      False      False     False     False    False   
2          False     False      False      False     False     False    False   
3          False     False      False      False     False     False    False   
4          False     False      False      False     False     False    False   
..           ...       ...        ...        ...       ...       ...      ...   
886        False     False      False      False     False     False    False   
887        False     False      False      False     False     False    False   
888        False     False      False      False     False     False    False   
889        False     False      False      False     False     False    False   
890        False     False      False      False     False     False    False   

     Embarked_C  Embarked_Q  Embarked_S  
0         False       False        True  
1          True       False       False  
2         False       False        True  
3         False       False        True  
4         False       False        True  
..          ...         ...         ...  
886       False       False        True  
887       False       False        True  
888       False       False        True  
889        True       False       False  
890       False        True       False  

[891 rows x 1732 columns]

## **Dataframe Concatenation and Merging**

A dataframe is a two-dimensional data structure having multiple rows and columns. In a dataframe, the data is aligned in the form of rows and columns only. A dataframe can perform arithmetic as well as conditional operations. It has mutable size.

concat() function does all of the heavy lifting of performing concatenation operations along an axis while performing optional set logic (union or intersection) of the indexes (if any) on the other axes.


In [74]:
# Python program to concatenate
# dataframes using Panda

# Creating first dataframe
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [75]:
# Creating second dataframe
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [76]:
# Creating third dataframe
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "E": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

df3

A    B    C    E
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [77]:
# Concatenating the dataframes
pd.concat([df1, df2, df3])

A    B    C    D    E
0    A0   B0   C0   D0  NaN
1    A1   B1   C1   D1  NaN
2    A2   B2   C2   D2  NaN
3    A3   B3   C3   D3  NaN
4    A4   B4   C4   D4  NaN
5    A5   B5   C5   D5  NaN
6    A6   B6   C6   D6  NaN
7    A7   B7   C7   D7  NaN
8    A8   B8   C8  NaN   D8
9    A9   B9   C9  NaN   D9
10  A10  B10  C10  NaN  D10
11  A11  B11  C11  NaN  D11

In [137]:
# Concatenating the dataframes by columns
# by default axis is 0 for rows you can change it for column

# Python program to concatenate
# dataframes using Panda

# Creating first dataframe
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

# Creating second dataframe
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[0, 1, 2, 3],
)

# Creating third dataframe
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[0, 1, 2, 4],
)

# Concatenating the dataframes
pd.concat([df1, df2, df3], axis=1)      # here axis = 1 means column 

A    B    C    D    A    B    C    D    A    B    C    D
0   A0   B0   C0   D0   A4   B4   C4   D4   A8   B8   C8   D8
1   A1   B1   C1   D1   A5   B5   C5   D5   A9   B9   C9   D9
2   A2   B2   C2   D2   A6   B6   C6   D6  A10  B10  C10  D10
3   A3   B3   C3   D3   A7   B7   C7   D7  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [79]:
# keep in mind for this index should be
pd.concat([df1, df2, df3], axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0   A0   B0   C0   D0   A4   B4   C4   D4   A8   B8   C8   D8
1   A1   B1   C1   D1   A5   B5   C5   D5   A9   B9   C9   D9
2   A2   B2   C2   D2   A6   B6   C6   D6  A10  B10  C10  D10
3   A3   B3   C3   D3   A7   B7   C7   D7  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

Pandas provides a single function, **merge()**, as the entry point for all standard database join operations between DataFrame objects.


In [145]:
# Python program to merge
# dataframes using Panda

# Dataframe created
import pandas as pd

left = pd.DataFrame(
    {
        "Key": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A4", "A2", "A3"],
        "B": ["B0", "B4", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
        "Key": ["K0", "K1", "K2", "K5"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)

left

Key   A   B
0  K0  A0  B0
1  K1  A4  B4
2  K2  A2  B2
3  K3  A3  B3

In [81]:
right

Key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K5  C3  D3

In [82]:
# Merging the dataframes
pd.merge(left, right, how="right", on="Key")

Key    A    B   C   D
0  K0   A0   B0  C0  D0
1  K1   A4   B4  C1  D1
2  K2   A2   B2  C2  D2
3  K5  NaN  NaN  C3  D3

In [146]:
pd.merge(left,right,how="left")

Key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K1  A4  B4   C1   D1
2  K2  A2  B2   C2   D2
3  K3  A3  B3  NaN  NaN